[package]
name = "bin"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ontology = { path = "../ontology" }

anyhow.workspace = true
clap.workspace = true
convert_case.workspace = true
csv.workspace = true
petgraph.workspace = true
serde_yaml.workspace = true

[lints]
workspace = true
