name: CI

on:
  push:
    branches:
      - main
    paths:
      - ecc/**
  pull_request:
    paths:
      - ecc/**

jobs:
  ecc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable && rustup default stable
      - run: cargo install --path crates/ecc-cli
      - run: ecc-cli ecc check