name: Commit Messages

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update nightly && rustup default nightly
      - name: Install `cocogitto`
        run: cargo install --locked cocogitto
      - run: cog check
